http:
  routers:
    myweb:
      service: webSite
      rule: "HOST(`badpyapple1.local`) && Path(`/`)"
    myapp1:
      service: app1
      rule: "HOST(`badpyapple1.local`) && Path(`/app1`)"
    myap3:
      service: app3
      rule: "HOST(`badpyapple2.local`) && Path(`/app3`)"
  services:
    webSite:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:1001"
          - url: "http://127.0.0.1:1002"

    app1:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:1001"
          - url: "http://127.0.0.1:1003"
    app3:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:1001"
          - url: "http://127.0.0.1:1003"
